print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/ralph/Documents/github/HotPatata/Assets/Models/balloon_shatter.mb"`)
{		
	file -o "/Users/ralph/Documents/github/HotPatata/Assets/Models/balloon_shatter.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/ralph/Documents/github/HotPatata/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/ralph/Documents/github/HotPatata/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/ralph/Documents/github/HotPatata/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
